### ISSUE TITLE
Feature Request: digital valve controlled by thermostat and clock

### ISSUE THREAD

**Issue by ttr** [Dubwise56/Dubs-Bad-Hygiene#11]
Hello,
Would be possible to have thermostat controlled digital valve (for central heating purposes).

One thermostat could be linked to one valve (multiple would be bit not logical - see below) while one valve van be controlled by multiple thermostats.
This is quite real life example form many Gas central heating houses (Ireland, Poland, UK). Each room can have wall mounted thermostat, and they send signal to loop valve to open and also to turn on heater. Dwellings might have multiple heating loops - one is always for tap hot water which is always on ; tap water is heated also as by product of radiator operation.

Another request will be to have smart thermostat (lets say +1 component form original) that would also have time controls - it will require time and temperature conditions to be true to trigger heating (logical AND)

This could enable more advanced but real life setup:
- would have separate loop for barracks (and bedrooms) that would have 1-3 thermostats placed (hallway, most far-side room, etc) and one valve separating it from mains and heater, they will also have time setting to enable them, in evening and disable during day
- separate loop for garden, hospital, kitchen (always on time wise)
- anther for workshops, but will different settings  (no issue if they run bit more colder
all of this could run from one electric/gas boiler

Why only one valve per thermo?
This goes down to how those valves are designed - some might have small motor that move mechanical valve (and they can be open close manually while draw power only when changing state, others are having electromagnetic pin and they draw power when they set to open, while cutting power would close them. They called Solenoid Valves.
In both cases, connecting multiple of them to power/signal would result that all of them are operated in same time.
So if X1 control uint would control valve A and B and X2 would control A and C, in fact if any of those control units would send signal all three valves will react.

This is not a case for multiple control using for one valve, especially in electromagnetic valves and in many cases with motor ones. In first one they send ON (open) signal or none (or even, they power them to open or not at all, so there is not conflict of signal. Very same to motor ones as signal means open but power is connected on separate wiring. Very old ones operated on principle of polarity switching - those would have issues.

For game I'll go with concept of electromagnetic ones. Would be simpler to implement on/off scenario (loosing power case might be more tricky) while not being able to manually control them and that they will use power while set to on would be a penalty for player.

**Comment by Dubwise56** [comment]
im afraid thats all a bit too complicated for a mod, people already struggle with just the idea of a single thermostat, the point of the radiators was to just slap rads in every room and basically forget about them from then on, and stick to electric heaters if you need fancy temperature controls in specific rooms, since the radiators max out at 21c and can't push a room any higher than that for simplicity

**Comment by ttr** [comment]
Oh no, thats fine (and this is old idea).
I've stopped using complex systems and dumb it whole down.
It might have some value to add thermostat on radiator (so when room is at temp they will not pull heat) but this will still need to somehow control heat source and possibly is pointless in grand total.

One small things i notices is that thermostat is set to 22, and heaters max out at 21, so w/o manual dropping it by 1 deg, thermostats have no real use.
Any chance You could see if changing default thermostat value to 21 would make sense ?

Thanks.
