### ISSUE TITLE
No Water Capacity in water tub

### ISSUE THREAD

**Issue by orbittwz** [Dubwise56/Dubs-Bad-Hygiene#12]
Hey!
I've built the basic Tub,Well,Latrine combo, but I cannot fill the tub with water from the well when needed...
Am I missing something?
![image](https://user-images.githubusercontent.com/45605734/71780701-8e932d80-2fce-11ea-969c-62b9b92064c8.png)

**Comment by orbittwz** [comment]
OK, the refill option appeared after reloading the game, and loading the save file again...
As mentioned in Discord, maybe the water tub code need a checkup??

**Comment by Dubwise56** [comment]
still looking into this bug

**Comment by Dubwise56** [comment]
This is probably just an issue with reservation, i added job failure messages on the right click for when no unreserved highest quality water source is available

**Comment by orbittwz** [comment]
Awesome! thank you very much Dubs!
