### ISSUE TITLE
Room Permissions

### ISSUE THREAD

**Issue by volak** [Dubwise56/Dubs-Bad-Hygiene#13]
Can you make it so toilets and showers designated for a specific bed are only usable for the owner (or current resident if using hospitality)?

My pawns tend to use whichever shower/toilet is closest to them 
which causes undesirable mood penalties when barging into someone's room to take a shower 

<img width="246" alt="sshot-9" src="https://user-images.githubusercontent.com/1750226/71867511-0d23c400-30d0-11ea-9100-2a8a89c8464c.png">

More generally though it would be nice to designate toilets and showers as public vs private

**Comment by Dubwise56** [comment]
its already set up like that, click on the fixture and click link bed, only owners of the bed are allowed to use the fixture no exceptions

**Comment by volak** [comment]
@Dubwise56  Hm strange.. is it possible that its only allowing 1 shower OR toilet?  I linked both to the bed but pawns keep barging in

**Comment by volak** [comment]
@Dubwise56 oh I think I figured out the problem.  If the bed is unassigned the pawns consider the fixtures free to use.  
Even though the fixtures are assigned to the bed, the bed is empty so they go ahead and grab a quick shower.

Can you update that to force them to ignore fixtures even if the bed is unassigned?

With hospitality the rooms are designated for "guests" and that apparently doesnt count as assigning the bed and the pawns barge into guest rooms for negative moods all around

**Comment by Dubwise56** [comment]
oh i see what you're saying, makes sense, changed for next patch
