### ISSUE TITLE
request: Pump from surface water

### ISSUE THREAD

**Issue by ornithoptercat** [Dubwise56/Dubs-Bad-Hygiene#15]
Why should I have to use a well and a pump (especially for high-demand crop irrigation) when I have a river right there?

The underground water also doesn't seem to notice where you have above-ground water, and ideally should.

**Comment by Dubwise56** [comment]
not sure what you mean, as you can see in the following screenshot rivers along with all other surface water are added to the water grid on map generation.
http://prntscr.com/qt0sq0

**Comment by ornithoptercat** [comment]
ok, i see the water is following after all. but why would I need a well+pump, instead of just a pump, if I've got a river there?

**Comment by Dubwise56** [comment]
it would take like 5 paragraphs to go over everything, but basically there's no difference between putting a well there or putting a pipe there, it would always have to calculate how much water is there in the same way, but would require an entire extra layer of calculating it and registering and deregisting all of the overlapping using and code doesn't grow on trees

**Comment by ornithoptercat** [comment]
that's a good reason, heh
