### ISSUE TITLE
disabled fuel boiler still consumes power

### ISSUE THREAD

**Issue by ttr** [Dubwise56/Dubs-Bad-Hygiene#16]
Not sure if this is intentional, but when I'd disable (designate toggle power) gas/chem fuel boiler, it does not generate heat (good), but fuel still is consumed.

My set up is that I have electric and chem boiler, thermostat and set of heaters - this is for my indoor farm. Electric heater is main one and chem one is planned to be used when power is out (or solar flare).
For that I keep it fueled while switched off and in said event, I'm planning to turn it on.

**Comment by Dubwise56** [comment]
thanks, fixed for next update
