### ISSUE TITLE
Pawns are drinking from ocean

### ISSUE THREAD

**Issue by jinlan** [Dubwise56/Dubs-Bad-Hygiene#18]
They directly drink from ocean, and also fill water tub with sea water. Look like sea water is a valid water source. It shouldn't be right?

**Comment by Dubwise56** [comment]
i think it originally ignored ocean water but some people considered them lakes so i just let them use it, but that was before i added thirst, maybe i'll block ocean water for drinking only in the next patch

**Comment by Dubwise56** [comment]
fixed
