### ISSUE TITLE
"Inspect string for washingmachine contains empty lines"

### ISSUE THREAD

**Issue by MoogieOuttaMyDepth** [Dubwise56/Dubs-Bad-Hygiene#23]
This error appears in the log when you click on a washing machine currently being repaired by a pawn.

Running on game version 1.1, mod build 2.7.1220

Full error text:

> Inspect string for WashingMachine309208 contains empty lines.
> 
> START
> Power needed: 10 W
> Grid excess/stored: 3220 W / 1591 Wd
> Broken down
> 
> Load: 0/5
> END
> Verse.Log:Error(String, Boolean)
> Verse.Log:ErrorOnce(String, Int32, Boolean)
> RimWorld.InspectPaneFiller:DrawInspectStringFor(ISelectable, Rect)
> RimWorld.InspectPaneFiller:DoPaneContentsFor(ISelectable, Rect)
> RimWorld.MainTabWindow_Inspect:DoPaneContents(Rect)
> RimWorld.InspectPaneUtility:InspectPaneOnGUI(Rect, IInspectPane)
> RimWorld.MainTabWindow_Inspect:DoWindowContents(Rect)
> Verse.Window:InnerWindowOnGUI(Int32)
> UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by Dubwise56** [comment]
should be fixed now
