### ISSUE TITLE
Nature's Pretty Sweet's "dirt paths" hide plumbing

### ISSUE THREAD

**Issue by lilwhitemouse** [Dubwise56/Dubs-Bad-Hygiene#25]
Nature's Pretty Sweet's "dirt paths" hide plumbing.  These are not "built" terrains - the pawns create them by walking on soil often enough.  While it makes sense for constructed floors, it perhaps does not for dirt paths.

(A different graphic with the pipe disappearing under raised dirt would be cool - I'm thinking of a little dirt ramp going up and over the pipe - but that's a lot more work than just showing the pipe.)

**Comment by lilwhitemouse** [comment]
The dirt paths are defined here:

https://github.com/tkkntkkn/natures-pretty-sweet/blob/master/1.1/Defs/Terrains.xml

Maybe there's something going on the with TerrainDef that would work better?

**Comment by Dubwise56** [comment]
my mod hides pipes based on the terrain layer, not much i can do if a mod uses the constructed layer rather than their own grid and layer system im afraid
