### ISSUE TITLE
Plumbing (pipe) blueprints block wall blueprints

### ISSUE THREAD

**Issue by lilwhitemouse** [Dubwise56/Dubs-Bad-Hygiene#26]
Pipe blueprints block wall blueprints:

Set down a line of pipe blueprint, and then try to set down a line of wall on top - space already occupied.

The game allows this for power conduits, so it's possible somehow?

**Comment by Dubwise56** [comment]
looked into it and its hardcoded for conduits, no def setting, so i can't do it without adding another harmony patch

**Comment by lilwhitemouse** [comment]
Well how rude of them.  It's not the biggest deal, obviously ;)

**Comment by Dubwise56** [comment]
fixed this in an update
