### ISSUE TITLE
Passive Cooler issues

### ISSUE THREAD

**Issue by dawnmist** [Dubwise56/Dubs-Bad-Hygiene#28]
1. Text in the options menu & its tooltip look like variable name text, rather than the actual strings to be displayed. Text shown: option = "PassiveWaterCoolersLink", tooltip = "PassiveWaterCoolersLinkTip". It took me a bit before I figured out that this was the option to turn off using water for refueling the passive coolers.
2. After turning off refueling by water, it is not possible to refuel the cooler by wood - right-clicking on the coolers shows the tooltip "Cannot refuel passive cooler - need wood" despite having 143 wood in the stockpile and another 100+ wood scattered around outside.
3. Refueling by water: there is no visual indicator that the cooler is in need of refueling, and pawns do not automatically queue up a refueling task for it.

I originally looked for an option to turn down the frequency of maintenance for the coolers - having to refill them daily with water instead of every 5 days felt too frequent, especially when there was no indication on the item when it needed refueling and pawns were not automatically queueing up refueling jobs. I didn't find a slider to affect that, so I tried turning it off entirely - but the ability to refuel them with wood at all was broken, so wood-fueled coolers last 5 days before being unusable/needing deconstruction to replace with a new cooler. Turning water refueling back on works but needs extensive micromanagement. It isn't possible to refuel them with wood when water refueling is turned off.

Running on Debian Linux 10 (Buster).

**Comment by Dubwise56** [comment]
new master is up for testing, fixed the missing text link, changed the way the passive water cooler works, it now uses the vanilla properties from the defs, so its exactly the same settings, also added the auto refuel toggle, and it should now work after toggling it on and off

**Comment by dawnmist** [comment]
I've tried testing by cloning master as a subdirectory of the Rimworld/Mods directory.

Water:
1. Option text is showing properly.
2. In-game, the passive coolers are showing x/50 (X days) == good.
3. No refueling tasks for refueling with water.
4. No visual indicator for a passive cooler that needs refueling.

Wood:
1. Turn off passive cooler needs water, then load a game => passive coolers still need water.
2. Turn off passive cooler needs water, then restart Rimworld => option is turned back on again at next load.

I cannot test refueling with wood as its inaccessible. If turned off at the Main Menu, then a game loaded without restarting Rimworld, they still require water. If turned off at the Main Menu, then restart Rimworld, the option is turned back on when the game restarts.

**Comment by Dubwise56** [comment]
pushed an update, all that stuff should be fixed now

**Comment by dawnmist** [comment]
I can confirm that it is now working as expected. Thank you very much for your time and effort! :)

**Comment by Dubwise56** [comment]
great, im just waiting for a bit more testing to be done on this update, and need to fix a couple more text strings here and there, then i can release it
