### ISSUE TITLE
Could not load UnityEngine.Texture2D at DBH/Things/Building/SewagePipe_Atlas_Blueprint in any active mod or in base resources.

### ISSUE THREAD

**Issue by Taranchuk** [Dubwise56/Dubs-Bad-Hygiene#3]
Another entry:

`Could not load UnityEngine.Texture2D at DBH/Things/Building/ducting_atlas_Blueprint in any active mod or in base resources.`

I searched the ducting_atlas_Blueprint and SewagePipe_Atlas_Blueprint  files in the mod folder and did not find them. Maybe they are missing in the github release?

**Comment by Dubwise56** [comment]
they should have been in there in the release
