### ISSUE TITLE
Missing space or newline character between "Blocked drain" and "For colony use".

### ISSUE THREAD

**Issue by CodePanter** [Dubwise56/Dubs-Bad-Hygiene#30]
I built a 'Simple Shower' and when it clogged I clicked on it. The left bottom information box showed 'Blocked Drain', but this was immediately followed by 'For colony use', there should be a space or newline character between those messages.

On a side note, I wanted to try and figure out how to fix this myself and offer it as a pull request, but you seem to have all the code locked away in a dll. Why is this? I'm new to rimworld modding, so this might just be 'the way people do it', but to me it seems it limits the amount people can contribute to your mods right?

**Comment by Dubwise56** [comment]
my background is in art and design and basically making a mod like the kind i make isn't a public effort like making an api tool for multiple companies to use to integrate systems like networking, its a creative work like making art or music, or like working on a car,  you don't walk into someones garage while they are working on their car and start tightening random bolts, you can observe that they missed a spot of grease but any more than that would be rude, i know hardcore open source coder types don't understand that but its just how it is in the creative world, also most people just want to steal your car.

I'll just fix the bug in the next update.

**Comment by CodePanter** [comment]
I hope I didn't come across as offensive, as mentioned I am new to modding and was just curious. I wasn't planning on stealing your car! I just wanted to point out this spot of grease. Thanks for fixing it in the next update.

**Comment by Dubwise56** [comment]
nah nah its fine i just often have to explain the creatives point of view to people that are used to the whole open source thing, already fixed and i'll be pushing the 1.2 update tonight probably
