### ISSUE TITLE
Z-Levels Integration

### ISSUE THREAD

**Issue by SonOfTheStars** [Dubwise56/Dubs-Bad-Hygiene#31]
Hello!

I am currently running both Bad Hygene and Z-Levels in a playthrough. It would be marvelous if you could add an integration with this mod so that we can bring Pipes/Aircon/Oil between different Z-Levels.

They have a "Power Column" to bring power between different levels in the original mod already, so this might be something to go by.

**Comment by mc-oofert** [comment]
probably wont happen

**Comment by Dubwise56** [comment]
added universal support for mods that add extra floors
