### ISSUE TITLE
Colonists washing each other tenderly in their sleep

### ISSUE THREAD

**Issue by Githubuser913** [Dubwise56/Dubs-Bad-Hygiene#32]
Colonists are sneaking into one another's bedrooms at night and washing each other in non-medical beds, without any medical issue or other disability preventing them from washing themselves. Same behavior towards Hospitality guests. I think it's only my pawns assigned to Doctor, and only when the target pawn is asleep. Here's a log. First time here so let me know if I can provide any other information. Thank you.

https://gist.github.com/f9af37e95cb81af7d9862f01c1dcda3d

**Comment by Dubwise56** [comment]
There's a mod thats messing with the vanilla checks for if someones a patient or not, what i might do is just make a copy of all of those vanilla methods so whatever has patched them doesn't interfere with my mod

**Comment by Dubwise56** [comment]
ok looking through your log it could be RimWorldChildren, i have someone testing a workaround now

**Comment by Githubuser913** [comment]
I recently removed babies and children and children, school, learning (way too many conflicts with normal mods between them) so I'll report if the issue persists

**Comment by Dubwise56** [comment]
ok i pushed the fix for it now
