### ISSUE TITLE
Thermostat's sub-zero constraints

### ISSUE THREAD

**Issue by AnnanFay** [Dubwise56/Dubs-Bad-Hygiene#34]
The thermostat doesn't go below 5C. Is this an oversight?

In cold regions you often want to set the desired temperature at about -21C to avoid infestations. As long as colonists have clothes then sub-zero isn't a big issue. Outside temperatures can get up to -70C, so it's important for heating systems to be able to heat buildings up to -20, or wherever you are aiming.

The real world implications of using radiators with _water_ to heat up buildings from sub-zero temperatures is interesting (since it doesn't work). However I feel this is a separate issue. Maybe oil-based heaters could be added, allowing working at lower temperatures, being more efficient and retaining heat for longer during blackouts.

As it is now, with boilers / radiators working fine at sub-zero temperatures I don't see why the thermostat doesn't work that low.

**Comment by Dubwise56** [comment]
if you want to make freezers then you would use freezer units

**Comment by AnnanFay** [comment]
> if you want to make freezers then you would use freezer units

The "Walk-in freezer unit"? I assume those could only cool down rooms.

Outside Temperature = -70C
Desired Inside Temperature = -20C

You want to heat the inside of my base from -70C to -20C.

**Comment by Dubwise56** [comment]
sorry i just reread this and see what you're saying now, this kind of setup isn't really what the central heating is intended for, you're meant to just place 1 room thermostat in the coldest part of your base so it kicks the boilers into action and gets all your room to a snuggly 21c like real life central heating, its a build it and forget about it kind of heating system for simplicity over many rooms.  For accurately controlling the temperature of specific rooms outside of the normal comfortable temperature ranges you would want to use vanilla electric heaters, which again is the kind of thing you would do in real life too like when you try to control damp and mold and stuff like that
