### ISSUE TITLE
A small medieval support requests.

### ISSUE THREAD

**Issue by f851374a** [Dubwise56/Dubs-Bad-Hygiene#4]
This mod generally works great in medieval runs with tech limiting mods, but i want to ask for few little changes:
1. Lower central heating research level to medieval so my colonists can stop complaining about cold water in bath :D . I know that central heating in how it implemented doesn't look medieval at all, but log boiler is already here, the whole plumbing system is already available for medieval tech, and making some kind of special pre-industrial central heating system probably doesn't worth an effort (such things existed btw, see [Hypocaust](https://en.wikipedia.org/wiki/Hypocaust))
2. Remove component requirement from non-powered pump. Components do not exist in medieval worlds, though some tech-limiting mods make a bad work for removing them completely.
3. Make log boiler support coal from Medieval times mod. Coal from this mod is main thing that keeps medieval colonies alive in places were wood is hard to acquire.

**Comment by Dubwise56** [comment]
components were removed from wind pumps, you can change stoves to coal yourself by changing the def, or just copy the log boiler and make it a coal boiler, and you can heat baths by placing a camp fire next to them!
