### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by abrenneke** [Dubwise56/Dubs-Bad-Hygiene#42]
Hi @Dubwise56! I really love all your mods. Why not open-source this mod (and your others too if they're not?) so that other people can contribute, and pick up the mod easier should you retire from RimWorld modding or die from a maneating goose? Most mods are open-source these days, it's awesome for the community!

Cheers,
Andy

**Comment by Dubwise56** [comment]
Cheers. Don't worry I'm not retiring or abandoning my mods, I have been around for a very long time now and do regular updates, and I'm not dying thank you very much, and even if I was my friends already have access to my repos, you don't want some random yahoo that has no idea what they are doing taking over my mods, the amount of times someone tells me they or someone else took over some complicated abandoned c# mod and they have absolutely no idea what they are doing, its a common problem with rimworld mods that get dumped. I'm also not looking for any contributions right now, you can suggest something and I'll review it, I need to write my own code and I hate having to decipher what other people hacked together especially when a bug comes up, I have a particular style.
