### ISSUE TITLE
Irrigation Sprinkler Null Error

### ISSUE THREAD

**Issue by NanoCE** [Dubwise56/Dubs-Bad-Hygiene#43]
Exception ticking IrrigationSprinkler1535805: System.NullReferenceException: Object reference not set to an instance of an object
  at DubsBadHygiene.CompIrrigationSprinkler.CompTick () [0x00011] in <62c18155b98d418aa2dd8002fa02e118>:0 
  at Verse.ThingWithComps.Tick () [0x00024] in <d72310b4d8f64d25aee502792b58549f>:0 
  at Verse.TickList.Tick () [0x0015c] in <d72310b4d8f64d25aee502792b58549f>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

This occurs when I try putting a sprinkler over a sun lamp. As this is allowed I assume this should be an intended feature. The sprinkler still works after the sprinkler is placed over the sun lamp.

**Comment by Dubwise56** [comment]
just tested it and it works fine for me in any combination, like  sprinkler first, lamp first, during spraying or after, no issues

**Comment by NanoCE** [comment]
When i posted this error I could replicate it but as of now I no longer can. Guess this is just a one time bug, sorry to waste your time.
