### ISSUE TITLE
Errors Related to Soil/Sprinklers with Save Our Ship 2

### ISSUE THREAD

**Issue by brucethemoose** [Dubwise56/Dubs-Bad-Hygiene#46]
Log: https://gist.github.com/HugsLibRecordKeeper/ae06c20cc7f2d4b85c9901374a4232da

Repro Steps: 

- Load Dubs Bad Hygiene and Save Our Ship 2. Order doesn't seem to matter.

- Enable the Dubs-SOS link in DBH settings. 

- Start a new colony with the "Derelict Station" scenario. 

- Errors will pop up when the map loads.

**Comment by Dubwise56** [comment]
looks like they are doing something weird with threading and sectionlayers, im about to push an update so i'll see if i can change when my textures load

**Comment by brucethemoose** [comment]
This seems to be fixed in the latest commit, thanks.
