### ISSUE TITLE
Full Water Tub error graphic

### ISSUE THREAD

**Issue by Wulfaskr** [Dubwise56/Dubs-Bad-Hygiene#52]
Not sure if this a native problem or a mod conflict.

Issue: water tubs have been showing a red graphic with a cross over them, but only when they have water in them. Empty water tubs have the normal empty water drop graphic.

Image showing both states of tub:
![image](https://user-images.githubusercontent.com/87223946/125156367-6d556380-e1a8-11eb-8349-61bbab2500e6.png)

I went through several pages of the workshop comments to see if anyone else had the issue but couldnt see it.
I have almost 300 mods installed which is why I thought its probably a mod conflict somewhere.
I did notice this in my game log which might help?
            Texture rectangle is out of bounds
             
            (Filename: C:\buildslave\unity\build\Runtime/Graphics/Image.cpp Line: 2361)

**Comment by Dubwise56** [comment]
think that ones docsworld causing it

**Comment by Wulfaskr** [comment]
Aiya! You are absolutely correct, my bad dude.
I've used them together for so long I forgot that tribal bucket texture wasn't native to DBH.


If anyone else is having this issue, its due to a missing texture in the Docsworld patch mixing Vanilla Farming Expanded and Dub's Bad Hygiene. It looks like it will be fixed in the next Docsworld release, but with the imminent release of 1.3 Ideology, i wouldnt hold my breath for that release. 
Interim fix is to go to (docsworldmodfolder)\Textures\Mod_Content\VFE_PD and duplicate the "DZ_BucketWater.png" and "DZ_BucketWater_m.png" files. 
Rename the copies to "DZ_BucketWater_water.png" and "DZ_BucketWater_water_m.png" respectively.
Strangely, disabling 'textures' in Docsworld settings didn't fix anything...
