### ISSUE TITLE
Bug: Irregular snow pattern

### ISSUE THREAD

**Issue by TinyGecko** [Dubwise56/Dubs-Bad-Hygiene#7]
When rain irrigation is turned on there will be an irregular snow pattern.
See this thread for more info and screenshot:
https://www.reddit.com/r/RimWorld/comments/e7x7fd/snow_settling_pattern_mod_help/

The mod No Water No Life has the same problem when it tries to apply a wet texture to the landscape. The workaround was replacing the irrigated texture with a blank one.

**Comment by Dubwise56** [comment]
should be fixed now
