### ISSUE TITLE
Stone mosaic tile labeled as flagstone

### ISSUE THREAD

**Issue by aph3rson** [Dubwise56/Dubs-Bad-Hygiene#78]
With the steel mosaic tile, the TerrainDef is correctly labeled as `mosaic tile`:

https://github.com/Dubwise56/Dubs-Bad-Hygiene/blob/b81a0c5bc140dc8700285ed55f120292d008ee79/1.3/Defs/ThingDefs_Buildings/Buildings5_Floors.xml#L9-L11

However, the stone versions of this tile are incorrectly labeled as `flagstone`, which is an [existing](https://rimworldwiki.com/wiki/Flagstone) terraindef in the base game. Example with sandstone:

https://github.com/Dubwise56/Dubs-Bad-Hygiene/blob/b81a0c5bc140dc8700285ed55f120292d008ee79/1.3/Defs/ThingDefs_Buildings/Buildings5_Floors.xml#L46-L48

This should be corrected. 

-----

Alternatively, is there a way to auto-generate the def name based on the input components? I think that'd just involve adding a `stuffCategories` to the base def, rather than defining your own defs, right?

**Comment by Dubwise56** [comment]
fixed
