### ISSUE TITLE
Feature Request: Move water bottles to XML

### ISSUE THREAD

**Issue by TinyGecko** [Dubwise56/Dubs-Bad-Hygiene#8]
Please make water bottles an xml entry to allow us making our own changes when needed (change stacklimit, edit bulk capacity for CE, xpath patches... ).

**Comment by Dubwise56** [comment]
i can't really do that because i don't want the bottles to exist if thirst is disabled, the defs can be changed in a plain static method that runs on startup though

**Comment by TinyGecko** [comment]
Can you provide instructions on how this can be achieved, please?

**Comment by Dubwise56** [comment]
something like this, i might look at reversing the code so the water bottle starts as a def then gets removed on load but i don't know if thats possible with mod settings, depends on the order things get run

    [StaticConstructorOnStartup]
    public static class PatchWater
    {
        static PatchWater()
        {
          var wb =  DefDatabase<ThingDef>.GetNamed("DBH_WaterBottle");
          wb.stackLimit = 500;
        }
    }

**Comment by TinyGecko** [comment]
But this method requires changing the assembly?
Okay, thank you!

**Comment by Dubwise56** [comment]
you can either change my dll in dlspy, or make your own dll in a mod, or add that code to an existing mod

**Comment by Dubwise56** [comment]
done some fiddling and looks like you can run xpath patches to change or remove defs based on mod settings so i moved the water bottles into a normal def for the next patch, i was just used to generating defs in code from my other mods so i used that method originally.

**Comment by TinyGecko** [comment]
That's great, thank you!
