### ISSUE TITLE
Some texts are not translatable & too short slider labels

### ISSUE THREAD

**Issue by Ragnar-F** [Dubwise56/Dubs-Bad-Hygiene#83]
Several issues I noticed while translating:

- Some texts in CompBaseWell.cs are not translatable. Specifically: "Sewage contamination", "Environment:", "Terrain:", "Things:"
- The spaces for the slider labels on the right side in the settings are unnecessarily narrow, making it difficult to read some labels that are forced to be longer due to its translation. The reason for this seems to be the generous allocation of space for the day/year specification of FertilizerLifeSpan. A simple solution would be to shorten texts like "240 days (3 years)" to "240d (3y)" and adjust the width accordingly.

**Comment by Dubwise56** [comment]
fixed for 1.4
