### ISSUE TITLE
Occupancy check with stall doors bugged in 1.4

### ISSUE THREAD

**Issue by Feirell** [Dubwise56/Dubs-Bad-Hygiene#87]
The occupancy check does not see to work with stall doors.
The stall doors do not limit the area of the occupancy check.

![grafik](https://user-images.githubusercontent.com/11183852/197517064-3103aa28-e6d4-47de-bd46-1b89dda84a4f.png)

This hinders the effectiveness of a public bathroom dramatically.

**Comment by Dubwise56** [comment]
they block line of sight for using the toilet, they do not create new rooms
